### ISSUE TITLE
Can you share the data used in your paper?

### ISSUE THREAD

**Issue by LiJijiname** [mitmedialab/PersonalizedMultitaskLearning#2]

**Comment by natashamjaques** [comment]
Thanks for your question. Unfortunately, the dataset for our paper

**Comment by natashamjaques** [comment]
Thank you for your question. Unfortunately, we are not allowed to share the data we used here, since it is highly identifiable, and is therefore protected by our research ethics board. However, there is a similar dataset that is freely available from Dartmouth, called the Student Life dataset: http://studentlife.cs.dartmouth.edu/dataset.html. There is also the Georgia Tech Campus Life dataset: http://www.quantifiedcampus.gatech.edu/. Both of these have data that is similar to what was used in our paper.

**Comment by LiJijiname** [comment]
Thanks very much.
